markdown: redcarpet
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: 鸡排斗士
subTitle: 开心就好
description:
url: https://lbwstco.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archive.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /about.html
    icon: icon-envelope-alt
    class: none
  - text: 联系我
    url: /contact.html
    icon: icon-heart
    class: none
  - text: 博客源代码
    url: https://github.com/lbwstco/lbwstco.github.io
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /about.html
    last: false

author:
  name: Kyrie
